#!/bin/bash
# Deploy aide-rap to a remote server
# 1. Pack project into ZIP (resolves symlinks)
# 2. Generate deploy.env from options (if any provided)
# 3. Upload ZIP + deploy.env via sftp (interactive password prompt)
#
# Usage:
#   ./deploy.sh                          # Upload ZIP only (keep existing deploy.env)
#   ./deploy.sh --base-path /irma        # Upload ZIP + deploy.env with base path
#   ./deploy.sh --port 18355 --system demo --base-path /demo
#
# Options:
#   --base-path <path>   Base URL path for reverse proxy (e.g., /irma)
#   --port <port>        Application port (default: 18354)
#   --pm2-name <name>    PM2 process name (default: aide-irma)
#   --system <name>      System name (default: irma)

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ZIP_NAME="aide-rap-latest.zip"
ZIP_PATH="/tmp/$ZIP_NAME"
DEPLOY_ENV_PATH="/tmp/deploy.env"
REMOTE_HOST="root@followthescore.org"
REMOTE_DIR="/var/www/vhosts/followthescore.org"

# Defaults
OPT_PM2_NAME="aide-irma"
OPT_PORT="18354"
OPT_SYSTEM="irma"
OPT_BASE_PATH=""
HAS_OPTIONS=false

# Parse arguments
while [ $# -gt 0 ]; do
    case "$1" in
        --base-path)
            OPT_BASE_PATH="$2"
            HAS_OPTIONS=true
            shift 2
            ;;
        --port)
            OPT_PORT="$2"
            HAS_OPTIONS=true
            shift 2
            ;;
        --pm2-name)
            OPT_PM2_NAME="$2"
            HAS_OPTIONS=true
            shift 2
            ;;
        --system)
            OPT_SYSTEM="$2"
            HAS_OPTIONS=true
            shift 2
            ;;
        *)
            echo "Unknown option: $1"
            echo "Usage: $0 [--base-path <path>] [--port <port>] [--pm2-name <name>] [--system <name>]"
            exit 1
            ;;
    esac
done

echo "=== AIDE RAP Deploy ==="
echo ""

# Step 1: Pack
echo "Packing..."
"$SCRIPT_DIR/pack.sh" "$ZIP_PATH"
if [ $? -ne 0 ]; then
    echo "ERROR: pack.sh failed"
    exit 1
fi
echo ""

# Step 2: Generate deploy.env (only if options were provided)
if [ "$HAS_OPTIONS" = true ]; then
    # Build APP_ARGS from options
    APP_ARGS=""
    if [ -n "$OPT_BASE_PATH" ]; then
        APP_ARGS="--base-path $OPT_BASE_PATH"
    fi

    cat > "$DEPLOY_ENV_PATH" <<ENVEOF
# Deployment config — generated by deploy.sh at $(date)
PM2_NAME="$OPT_PM2_NAME"
PORT=$OPT_PORT
SYSTEM="$OPT_SYSTEM"
APP_ARGS="$APP_ARGS"
ENVEOF

    echo "Generated deploy.env:"
    cat "$DEPLOY_ENV_PATH"
    echo ""
fi

# Step 3: Upload via sftp (password prompted interactively)
echo "Uploading to $REMOTE_HOST:$REMOTE_DIR/ ..."
echo "  (Enter password when prompted)"
echo ""

if [ "$HAS_OPTIONS" = true ]; then
    sftp "$REMOTE_HOST" <<EOF
put "$ZIP_PATH" "$REMOTE_DIR/$ZIP_NAME"
put "$DEPLOY_ENV_PATH" "$REMOTE_DIR/deploy.env"
quit
EOF
else
    sftp "$REMOTE_HOST" <<EOF
put "$ZIP_PATH" "$REMOTE_DIR/$ZIP_NAME"
quit
EOF
fi

if [ $? -ne 0 ]; then
    echo "ERROR: sftp upload failed"
    exit 1
fi

echo ""
echo "Upload complete."
if [ "$HAS_OPTIONS" = true ]; then
    echo "  ZIP + deploy.env uploaded."
else
    echo "  ZIP uploaded (deploy.env unchanged on server)."
fi
echo "Use the Re-Install button in the Admin panel to deploy."
